function Gxtapp(){var cb='',_=' top: -1000px;',zb='" for "gwt:onLoadErrorFn"',xb='" for "gwt:onPropertyErrorFn"',ib='");',Ab='#',bd='.cache.js',Cb='/',Ib='//',oc='8D0EA8567B81367B8B8A9E8CFD6B86A4',ad=':',pc=':1',qc=':10',rc=':11',sc=':12',tc=':13',uc=':14',vc=':15',wc=':16',xc=':17',yc=':18',zc=':19',Ac=':2',Bc=':20',Cc=':21',Dc=':22',Ec=':23',Fc=':24',Gc=':25',Hc=':26',Ic=':27',Jc=':28',Kc=':29',Lc=':3',Mc=':30',Nc=':31',Oc=':32',Pc=':33',Qc=':34',Rc=':35',Sc=':36',Tc=':37',Uc=':38',Vc=':39',Wc=':4',Xc=':5',Yc=':6',Zc=':7',$c=':8',_c=':9',rb='::',pd=':moduleBase',bb='<!doctype html>',db='<html><head><\/head><body><\/body><\/html>',ub='=',Bb='?',wb='Bad handler "',ab='CSS1Compat',gb='Chrome',fb='DOMContentLoaded',W='DUMMY',U='Gxtapp',nc='Gxtapp.devmode.js',Gb='Gxtapp.nocache.js',qb='Gxtapp::',od='Ignoring non-whitelisted Dev Mode URL: ',nd='__gwtDevModeHook:Gxtapp',md='_gwt_dummy_',cc='adobeair',dc='air',Hb='base',Fb='baseUrl',R='begin',X='body',Q='bootstrap',Kb='chrome',Eb='clear.cache.gif',tb='content',jd='end',hb='eval("',ld='file:',$b='gecko',ac='gecko1_8',bc='gecko1_9',S='gwt.codesvr.Gxtapp=',T='gwt.codesvr=',yb='gwt:onLoadErrorFn',vb='gwt:onPropertyErrorFn',sb='gwt:property',Jb='gxt.user.agent',nb='head',fd='href',kd='http:',Nb='ie10',Tb='ie6',Rb='ie7',Pb='ie8',Ob='ie9',Y='iframe',Db='img',kb='javascript',Z='javascript:""',cd='link',ic='linux',gd='loadExternalRefs',hc='mac',gc='mac os x',fc='macintosh',ob='meta',mb='moduleRequested',lb='moduleStartup',Mb='msie',Sb='msie 6',Qb='msie 7',pb='name',Lb='opera',$='position:absolute; width:0; height:0; border:none; left: -1000px;',dd='rel',hd='reset.css',_b='rv:1.8',Ub='safari',Wb='safari3',Yb='safari4',Zb='safari5',jb='script',mc='selectingPermutation',V='startup',ed='stylesheet',eb='undefined',lc='unknown',ec='user.agent.os',Vb='version/3',Xb='version/4',kc='win32',jc='windows';var o=window;var p=document;r(Q,R);function q(){var a=o.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:U,sessionId:o.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
Gxtapp.__sendStats=r;Gxtapp.__moduleName=U;Gxtapp.__errFn=null;Gxtapp.__moduleBase=W;Gxtapp.__softPermutationId=0;Gxtapp.__computePropValue=null;Gxtapp.__getPropMap=null;Gxtapp.__gwtInstallCode=function(){};Gxtapp.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[U]={moduleName:U};var v;function w(){B();return v}
function A(){B();return v.getElementsByTagName(X)[0]}
function B(){if(v){return}var a=p.createElement(Y);a.src=Z;a.id=U;a.style.cssText=$+_;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==ab?bb:cb;v.write(b+db);v.close()}
function C(k){function l(a){function b(){if(typeof p.readyState==eb){return typeof p.body!=eb&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(fb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(fb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=w();var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(hb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(ib));g=f.createElement(jb);g.language=kb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(jb);g.language=kb;g.text=c[i];e.appendChild(g);d(e,g)}}}
Gxtapp.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;p.getElementsByTagName(nb)[0].appendChild(n)}
Gxtapp.__startLoadingFragment=function(a){return G(a)};Gxtapp.__installRunAsyncCode=function(a){var b=A();var c=w().createElement(jb);c.language=kb;c.text=a;b.appendChild(c);b.removeChild(c)};function D(){var c={};var d;var e;var f=p.getElementsByTagName(ob);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(pb),k;if(j){j=j.replace(qb,cb);if(j.indexOf(rb)>=0){continue}if(j==sb){k=i.getAttribute(tb);if(k){var l,m=k.indexOf(ub);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=cb}c[j]=l}}else if(j==vb){k=i.getAttribute(tb);if(k){try{d=eval(k)}catch(a){alert(wb+k+xb)}}}else if(j==yb){k=i.getAttribute(tb);if(k){try{e=eval(k)}catch(a){alert(wb+k+zb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;Gxtapp.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Ab);if(b==-1){b=a.length}var c=a.indexOf(Bb);if(c==-1){c=a.length}var d=a.lastIndexOf(Cb,Math.min(c,b));return d>=0?a.substring(0,d+1):cb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Db);b.src=a+Eb;a=e(b.src)}return a}
function g(){var a=t(Fb);if(a!=null){return a}return cb}
function h(){var a=p.getElementsByTagName(jb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Gb)!=-1){return e(a[b].src)}}return cb}
function i(){var a=p.getElementsByTagName(Hb);if(a.length>0){return a[a.length-1].href}return cb}
function j(){var a=p.location;return a.href==a.protocol+Ib+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==cb){k=h()}if(k==cb){k=i()}if(k==cb&&j()){k=e(p.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return Gxtapp.__moduleBase+a}
function H(){var f=[];var g=0;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Jb]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Kb)!=-1)return Kb;if(a.indexOf(Lb)!=-1)return Lb;if(a.indexOf(Mb)!=-1){if(p.documentMode>=10)return Nb;if(p.documentMode>=9)return Ob;if(p.documentMode>=8)return Pb;if(a.indexOf(Qb)!=-1)return Rb;if(a.indexOf(Sb)!=-1)return Tb;return Nb}if(a.indexOf(Ub)!=-1){if(a.indexOf(Vb)!=-1)return Wb;if(a.indexOf(Xb)!=-1)return Yb;return Zb}if(a.indexOf($b)!=-1){if(a.indexOf(_b)!=-1)return ac;return bc}if(a.indexOf(cc)!=-1)return dc;return null};i[Jb]={air:0,chrome:1,gecko1_8:2,gecko1_9:3,ie10:4,ie8:5,ie9:6,safari3:7,safari4:8,safari5:9};j[ec]=function(){var a=o.navigator.userAgent.toLowerCase();if(a.indexOf(fc)!=-1||a.indexOf(gc)!=-1){return hc}if(a.indexOf(ic)!=-1){return ic}if(a.indexOf(jc)!=-1||a.indexOf(kc)!=-1){return jc}return lc};i[ec]={linux:0,mac:1,unknown:2,windows:3};s=function(a,b){return b in i[a]};Gxtapp.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};Gxtapp.__computePropValue=k;o.__gwt_activeModules[U].bindings=Gxtapp.__getPropMap;r(Q,mc);if(q()){return G(nc)}var l;try{h([dc,ic],oc);h([dc,hc],oc+pc);h([ac,lc],oc+qc);h([ac,jc],oc+rc);h([bc,ic],oc+sc);h([bc,hc],oc+tc);h([bc,lc],oc+uc);h([bc,jc],oc+vc);h([Nb,ic],oc+wc);h([Nb,hc],oc+xc);h([Nb,lc],oc+yc);h([Nb,jc],oc+zc);h([dc,lc],oc+Ac);h([Pb,ic],oc+Bc);h([Pb,hc],oc+Cc);h([Pb,lc],oc+Dc);h([Pb,jc],oc+Ec);h([Ob,ic],oc+Fc);h([Ob,hc],oc+Gc);h([Ob,lc],oc+Hc);h([Ob,jc],oc+Ic);h([Wb,ic],oc+Jc);h([Wb,hc],oc+Kc);h([dc,jc],oc+Lc);h([Wb,lc],oc+Mc);h([Wb,jc],oc+Nc);h([Yb,ic],oc+Oc);h([Yb,hc],oc+Pc);h([Yb,lc],oc+Qc);h([Yb,jc],oc+Rc);h([Zb,ic],oc+Sc);h([Zb,hc],oc+Tc);h([Zb,lc],oc+Uc);h([Zb,jc],oc+Vc);h([Kb,ic],oc+Wc);h([Kb,hc],oc+Xc);h([Kb,lc],oc+Yc);h([Kb,jc],oc+Zc);h([ac,ic],oc+$c);h([ac,hc],oc+_c);l=f[k(Jb)][k(ec)];var m=l.indexOf(ad);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}Gxtapp.__softPermutationId=g;return G(l+bd)}
function I(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(cd);b.setAttribute(dd,ed);b.setAttribute(fd,G(a));p.getElementsByTagName(nb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(gd,R);c(hd);r(gd,jd)}
D();Gxtapp.__moduleBase=F();u[U].moduleBase=Gxtapp.__moduleBase;var J=H();if(o){var K=!!(o.location.protocol==kd||o.location.protocol==ld);o.__gwt_activeModules[U].canRedirect=K;function L(){var b=md;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=nd;var N=o.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(od+N)}N=cb}if(N&&!o[M]){o[M]=true;o[M+pd]=F();var O=p.createElement(jb);O.src=N;var P=p.getElementsByTagName(nb)[0];P.insertBefore(O,P.firstElementChild||P.children[0]);return false}}}I();r(Q,jd);C(J);return true}
Gxtapp.succeeded=Gxtapp();